package commands

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/HundredAcreStudio/vor/internal/persistence/repos"
)

// HTML-comment markers identical to the Python implementation so the
// same file can be re-generated by either tool without losing the
// user's hand-edited content.
const (
	claudeMarkerStart = "<!-- VOR:START — Do not edit below this line. Auto-generated by Vor. -->"
	claudeMarkerEnd   = "<!-- VOR:END -->"
)

// claudeUserPlaceholder is the default content written above the
// markers when CLAUDE.md doesn't exist yet. Matches the Python version.
const claudeUserPlaceholder = `# CLAUDE.md

<!-- Add your custom instructions below. Vor will never modify anything outside the VOR markers. -->
<!-- Examples: coding style rules, test commands, workflow preferences, constraints -->
`

// newClaudeMdCmd writes <repo>/CLAUDE.md with vor-managed
// codebase context between marker comments. Content above the
// VOR:START marker is left untouched on update.
func newClaudeMdCmd() *cobra.Command {
	var (
		repoPath   string
		outputPath string
		toStdout   bool
	)
	cmd := &cobra.Command{
		Use:     "claude-md [PATH]",
		Aliases: []string{"generate-claude-md"},
		Short:   "Generate or update <repo>/CLAUDE.md with codebase intelligence context",
		Long: `Writes <repo>/CLAUDE.md with a managed section that
summarises this repo's indexed state — file counts, top hotspots,
decision records, health verdict, and the MCP tools reference. Content
above the VOR:START marker is preserved across re-runs.

Use --stdout to preview the rendered output without writing.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()
			root := repoPath
			if len(args) > 0 {
				root = args[0]
			}
			absRoot, err := filepath.Abs(root)
			if err != nil {
				return fmt.Errorf("resolve path: %w", err)
			}
			conn, _, err := openDB(ctx, root)
			if err != nil {
				return err
			}
			defer conn.Close()

			repoRow, err := repos.New(conn).EnsureByLocalPath(ctx, absRoot, "")
			if err != nil {
				return fmt.Errorf("locate repo: %w", err)
			}

			data, err := collectClaudeMdData(ctx, conn, repoRow.ID, absRoot)
			if err != nil {
				return fmt.Errorf("collect data: %w", err)
			}
			managed := renderClaudeMdManaged(data)

			if toStdout {
				wrapped := claudeUserPlaceholder + "\n" + claudeMarkerStart + "\n" + managed + claudeMarkerEnd + "\n"
				fmt.Fprint(cmd.OutOrStdout(), wrapped)
				return nil
			}

			dest := outputPath
			if dest == "" {
				dest = filepath.Join(absRoot, "CLAUDE.md")
			} else {
				dest, err = filepath.Abs(dest)
				if err != nil {
					return fmt.Errorf("resolve output path: %w", err)
				}
			}
			if err := writeClaudeMd(dest, managed); err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%s updated\n", dest)
			return nil
		},
	}
	cmd.Flags().StringVar(&repoPath, "repo", ".", "repository path (overridden by positional PATH)")
	cmd.Flags().StringVarP(&outputPath, "output", "o", "", "output path (default <repo>/CLAUDE.md)")
	cmd.Flags().BoolVar(&toStdout, "stdout", false, "print to stdout instead of writing the file")
	return cmd
}

// regenerateClaudeMd runs the data collection + merge that the
// claude-md command does, but with no flag handling — meant to be
// called from init/update so users don't need a separate command
// invocation to keep CLAUDE.md in sync with the indexed state.
//
// Errors here are non-fatal at the call site: a broken CLAUDE.md
// regen shouldn't block a successful re-index. The caller is
// expected to surface the error as a warning, not propagate it.
func regenerateClaudeMd(ctx context.Context, conn *sql.DB, repoID, absRoot string) error {
	data, err := collectClaudeMdData(ctx, conn, repoID, absRoot)
	if err != nil {
		return fmt.Errorf("collect data: %w", err)
	}
	managed := renderClaudeMdManaged(data)
	dest := filepath.Join(absRoot, "CLAUDE.md")
	return writeClaudeMd(dest, managed)
}

// claudeMdData is the projection feed for the template. Light and
// nullable — missing pieces just render as empty sections.
type claudeMdData struct {
	RepoName       string
	IndexedAt      string
	IndexedCommit  string
	FileCount      int
	SymbolCount    int
	EntryPoints    []string
	Hotspots       []claudeMdHotspot
	Decisions      []claudeMdDecision
	HealthFindings int
	HealthByMarker map[string]int
	PageCount      int
}

type claudeMdHotspot struct {
	Path           string
	CommitCount90d int
	Owner          string
}

type claudeMdDecision struct {
	Title    string
	Source   string
	Evidence string
}

// collectClaudeMdData runs the read-only queries that feed the template.
// Failures on optional sections are tolerated — return what we have.
func collectClaudeMdData(ctx context.Context, conn *sql.DB, repoID, absRoot string) (claudeMdData, error) {
	d := claudeMdData{
		RepoName:  filepath.Base(absRoot),
		IndexedAt: time.Now().UTC().Format("2006-01-02 15:04:05Z"),
	}

	// indexed_commit lives on repositories.head_commit.
	var headCommit sql.NullString
	_ = conn.QueryRowContext(ctx,
		`SELECT COALESCE(head_commit, '') FROM repositories WHERE id = ?`, repoID).Scan(&headCommit)
	if headCommit.Valid && headCommit.String != "" {
		d.IndexedCommit = headCommit.String
		if len(d.IndexedCommit) > 12 {
			d.IndexedCommit = d.IndexedCommit[:12]
		}
	}

	_ = conn.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM graph_nodes WHERE repository_id = ? AND node_type = 'file'`, repoID).Scan(&d.FileCount)
	_ = conn.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM graph_nodes WHERE repository_id = ? AND node_type != 'file'`, repoID).Scan(&d.SymbolCount)
	_ = conn.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM wiki_pages WHERE repository_id = ?`, repoID).Scan(&d.PageCount)

	// Entry points (top 10).
	rows, err := conn.QueryContext(ctx, `
		SELECT COALESCE(file_path, node_id)
		FROM graph_nodes
		WHERE repository_id = ? AND is_entry_point = 1 AND node_type = 'file'
		ORDER BY node_id LIMIT 10
	`, repoID)
	if err == nil {
		for rows.Next() {
			var p string
			if err := rows.Scan(&p); err == nil && p != "" {
				d.EntryPoints = append(d.EntryPoints, p)
			}
		}
		_ = rows.Close()
	}

	// Hotspots: top 10 by churn_percentile DESC.
	hsRows, err := conn.QueryContext(ctx, `
		SELECT file_path, commit_count_90d, COALESCE(primary_owner_name, '')
		FROM git_metadata
		WHERE repository_id = ? AND is_hotspot = 1
		ORDER BY churn_percentile DESC, commit_count_90d DESC
		LIMIT 10
	`, repoID)
	if err == nil {
		for hsRows.Next() {
			var h claudeMdHotspot
			if err := hsRows.Scan(&h.Path, &h.CommitCount90d, &h.Owner); err == nil {
				d.Hotspots = append(d.Hotspots, h)
			}
		}
		_ = hsRows.Close()
	}

	// Decisions: top 10 by confidence.
	drRows, err := conn.QueryContext(ctx, `
		SELECT title, source, COALESCE(evidence_file, '')
		FROM decision_records
		WHERE repository_id = ?
		ORDER BY confidence DESC, evidence_file
		LIMIT 10
	`, repoID)
	if err == nil {
		for drRows.Next() {
			var dr claudeMdDecision
			if err := drRows.Scan(&dr.Title, &dr.Source, &dr.Evidence); err == nil {
				d.Decisions = append(d.Decisions, dr)
			}
		}
		_ = drRows.Close()
	}

	// Health: total findings + grouped by biomarker.
	_ = conn.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM health_findings WHERE repository_id = ?`, repoID).Scan(&d.HealthFindings)
	hbRows, err := conn.QueryContext(ctx, `
		SELECT biomarker_type, COUNT(*)
		FROM health_findings WHERE repository_id = ?
		GROUP BY biomarker_type ORDER BY 2 DESC
	`, repoID)
	if err == nil {
		d.HealthByMarker = map[string]int{}
		for hbRows.Next() {
			var k string
			var n int
			if err := hbRows.Scan(&k, &n); err == nil {
				d.HealthByMarker[k] = n
			}
		}
		_ = hbRows.Close()
	}
	return d, nil
}

// renderClaudeMdManaged returns the markdown content between START/END
// markers. Markers themselves are added by writeClaudeMd.
func renderClaudeMdManaged(d claudeMdData) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## IMPORTANT: Codebase Intelligence Instructions for %s\n\n", d.RepoName)
	b.WriteString("> This repository is indexed by [Vor](https://github.com/HundredAcreStudio/vor).\n")
	b.WriteString("> The MCP tools below answer from the index in one call — use them instead of\n")
	b.WriteString("> grepping or reading dozens of files to orient. **Always verify against the\n")
	b.WriteString("> actual source before changing code** — the index may be stale.\n>\n")
	b.WriteString("> **Reach for them proactively:**\n")
	b.WriteString("> - **Before editing any file** (especially shared utilities or core modules, or\n")
	b.WriteString(">   files the user didn't name): call `vor_risk` first — it reports the blast\n")
	b.WriteString(">   radius (dependents), co-change partners, ownership/bus-factor, and the\n")
	b.WriteString(">   architectural decisions that govern the file. Warn the user on high risk.\n")
	b.WriteString("> - **Getting oriented / \"where is X\"**: `vor_status`, then `vor_get_context` on\n")
	b.WriteString(">   the files you're about to touch.\n")
	b.WriteString("> - **Before refactoring or diverging from a pattern**: `vor_get_why` to find the\n")
	b.WriteString(">   decision behind the current shape.\n")
	b.WriteString("> - **\"How does X work\" / \"where is Y handled\"**: `vor_get_answer`.\n")
	b.WriteString("> - **Tracing impact / call flow**: `vor_get_dependency_path`, `vor_get_execution_flows`.\n\n")
	fmt.Fprintf(&b, "Last indexed: %s", d.IndexedAt)
	if d.IndexedCommit != "" {
		fmt.Fprintf(&b, " (commit %s)", d.IndexedCommit)
	}
	b.WriteString(".\n\n")

	fmt.Fprintf(&b, "## Indexed state\n\n")
	fmt.Fprintf(&b, "- **Files indexed**: %d\n", d.FileCount)
	fmt.Fprintf(&b, "- **Symbols indexed**: %d\n", d.SymbolCount)
	fmt.Fprintf(&b, "- **Wiki pages generated**: %d\n", d.PageCount)
	fmt.Fprintf(&b, "- **Health findings**: %d\n", d.HealthFindings)
	if len(d.HealthByMarker) > 0 {
		// Sort by name so re-runs produce byte-identical output (Go
		// map iteration order is randomised otherwise).
		keys := make([]string, 0, len(d.HealthByMarker))
		for k := range d.HealthByMarker {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("  - ")
		for i, k := range keys {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%s=%d", k, d.HealthByMarker[k])
		}
		b.WriteByte('\n')
	}
	b.WriteByte('\n')

	if len(d.EntryPoints) > 0 {
		b.WriteString("## Entry points\n\n")
		for _, ep := range d.EntryPoints {
			fmt.Fprintf(&b, "- `%s`\n", ep)
		}
		b.WriteByte('\n')
	}

	if len(d.Hotspots) > 0 {
		b.WriteString("## Hotspots (high churn, last 90 days)\n\n")
		b.WriteString("| File | 90d commits | Owner |\n")
		b.WriteString("|------|-------------|-------|\n")
		for _, h := range d.Hotspots {
			owner := h.Owner
			if owner == "" {
				owner = "—"
			}
			fmt.Fprintf(&b, "| `%s` | %d | %s |\n", h.Path, h.CommitCount90d, owner)
		}
		b.WriteByte('\n')
	}

	if len(d.Decisions) > 0 {
		b.WriteString("## Architectural decisions (top by confidence)\n\n")
		for _, dr := range d.Decisions {
			evidence := dr.Evidence
			if evidence == "" {
				evidence = "(no source evidence)"
			}
			fmt.Fprintf(&b, "- **%s** _(%s — %s)_\n", dr.Title, dr.Source, evidence)
		}
		b.WriteByte('\n')
	}

	b.WriteString(mcpToolsReference)
	return b.String()
}

// mcpToolsReference is the static MCP tools section. Kept lockstep with
// the Python template's text so the same file content can be produced
// by either implementation.
const mcpToolsReference = `## Vor MCP tools

This repo's Go server exposes the same tool surface over MCP. Each
response carries provenance + freshness so the agent can decide whether
to verify against source.

| Tool                                  | What it answers                                                |
|---------------------------------------|----------------------------------------------------------------|
| ` + "`vor_risk`" + `                       | **Before editing:** blast radius, owners, governing decisions. |
| ` + "`vor_get_context`" + `                | Triage card for files/symbols (summary, hotspot, decisions).   |
| ` + "`vor_get_why`" + `                    | The architectural decision behind why code is shaped this way. |
| ` + "`vor_get_answer`" + `                 | Synthesized answer to a natural-language question about code.  |
| ` + "`vor_status`" + `                     | Repository summary (counts, hotspots, health average).         |
| ` + "`vor_hotspots`" + `                   | High-churn files with owners and bus factor.                   |
| ` + "`vor_dead_code`" + `                  | Unreachable files / symbols with safe-to-delete flags.         |
| ` + "`vor_health` + `vor_health_findings`" + ` | Code-health scores and biomarker findings.            |
| ` + "`vor_decisions`" + `                  | Architectural decisions from markers, ADRs, CHANGELOG, commits.|
| ` + "`vor_get_dependency_path` + `vor_get_execution_flows`" + ` | Trace how code reaches / flows through other code. |
| ` + "`vor_pages` + `vor_page`" + `    | Generated wiki page summaries and full content.                |
| ` + "`vor_search`" + `                     | Find symbols by name across the indexed repo.                  |
| ` + "`vor_pipeline_log`" + `               | Recent pipeline phase executions (observability).              |
`

// writeClaudeMd merges the managed section into dest, preserving any
// user content above the START marker. Creates parents on demand.
func writeClaudeMd(dest, managed string) error {
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	existing, err := os.ReadFile(dest)
	if errors.Is(err, os.ErrNotExist) {
		out := claudeUserPlaceholder + "\n" + claudeMarkerStart + "\n" + managed + claudeMarkerEnd + "\n"
		return os.WriteFile(dest, []byte(out), 0o644)
	}
	if err != nil {
		return err
	}
	merged := mergeClaudeMd(string(existing), managed)
	// Idempotent: when the only difference from the existing file is the
	// "Last indexed" timestamp, skip the write so committed CLAUDE.md
	// files don't churn on every re-index.
	if stripIndexedLine(merged) == stripIndexedLine(string(existing)) {
		return nil
	}
	return os.WriteFile(dest, []byte(merged), 0o644)
}

// stripIndexedLine removes the volatile "Last indexed: …" line so two
// renders can be compared for meaningful (non-timestamp) changes.
func stripIndexedLine(s string) string {
	lines := strings.Split(s, "\n")
	out := lines[:0]
	for _, ln := range lines {
		if strings.HasPrefix(strings.TrimSpace(ln), "Last indexed:") {
			continue
		}
		out = append(out, ln)
	}
	return strings.Join(out, "\n")
}

// mergeClaudeMd preserves content outside the marker pair and replaces
// the inside. If the existing file has no markers, the managed block is
// appended at the bottom.
func mergeClaudeMd(existing, managed string) string {
	startIdx := strings.Index(existing, claudeMarkerStart)
	endIdx := strings.Index(existing, claudeMarkerEnd)
	if startIdx >= 0 && endIdx >= 0 && endIdx > startIdx {
		head := existing[:startIdx]
		tail := existing[endIdx+len(claudeMarkerEnd):]
		// Normalise the seam so there's one blank line on each side of
		// the markers (no infinite stacking on repeated runs).
		head = strings.TrimRight(head, "\n") + "\n\n"
		if tail = strings.TrimLeft(tail, "\n"); tail != "" {
			tail = "\n" + tail
		} else {
			// Keep a single trailing newline after END so the framing
			// matches the freshly-created file — otherwise the first
			// merge after creation would rewrite just to drop it.
			tail = "\n"
		}
		return head + claudeMarkerStart + "\n" + managed + claudeMarkerEnd + tail
	}
	// No markers: append.
	separator := "\n\n"
	if !strings.HasSuffix(existing, "\n") {
		separator = "\n\n"
	}
	return existing + separator + claudeMarkerStart + "\n" + managed + claudeMarkerEnd + "\n"
}
