package commands_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClaudeMd_WritesNewFile(t *testing.T) {
	tmp, _, _ := repoFixture(t)
	if _, _, err := runRepowiseCmd(t, nil, "update", tmp); err != nil {
		t.Fatal(err)
	}
	if _, _, err := runRepowiseCmd(t, nil, "claude-md", tmp); err != nil {
		t.Fatalf("claude-md: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(tmp, "CLAUDE.md"))
	if err != nil {
		t.Fatalf("read CLAUDE.md: %v", err)
	}
	s := string(body)
	for _, want := range []string{
		"REPOWISE:START",
		"REPOWISE:END",
		"Codebase Intelligence Instructions",
		"Repowise MCP tools",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("CLAUDE.md missing %q", want)
		}
	}
}

func TestClaudeMd_PreservesUserContent(t *testing.T) {
	tmp, _, _ := repoFixture(t)
	if _, _, err := runRepowiseCmd(t, nil, "update", tmp); err != nil {
		t.Fatal(err)
	}
	// Pre-create CLAUDE.md with user content + the managed block.
	dest := filepath.Join(tmp, "CLAUDE.md")
	initial := "# CLAUDE.md\n\nMy custom notes — never touch.\n\n" +
		"<!-- REPOWISE:START — Do not edit below this line. Auto-generated by Repowise. -->\n" +
		"old auto content\n" +
		"<!-- REPOWISE:END -->\n"
	if err := os.WriteFile(dest, []byte(initial), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, _, err := runRepowiseCmd(t, nil, "claude-md", tmp); err != nil {
		t.Fatalf("claude-md: %v", err)
	}
	body, _ := os.ReadFile(dest)
	s := string(body)
	if !strings.Contains(s, "My custom notes — never touch.") {
		t.Error("user content above marker was clobbered")
	}
	if strings.Contains(s, "old auto content") {
		t.Error("stale managed content survived re-generation")
	}
	if !strings.Contains(s, "Repowise MCP tools") {
		t.Error("new managed block missing MCP tools section")
	}
}

func TestClaudeMd_AppendsWhenMarkersAbsent(t *testing.T) {
	tmp, _, _ := repoFixture(t)
	if _, _, err := runRepowiseCmd(t, nil, "update", tmp); err != nil {
		t.Fatal(err)
	}
	dest := filepath.Join(tmp, "CLAUDE.md")
	initial := "# CLAUDE.md\n\nNo markers here yet.\n"
	_ = os.WriteFile(dest, []byte(initial), 0o644)

	if _, _, err := runRepowiseCmd(t, nil, "claude-md", tmp); err != nil {
		t.Fatal(err)
	}
	body, _ := os.ReadFile(dest)
	s := string(body)
	if !strings.HasPrefix(s, "# CLAUDE.md\n\nNo markers here yet.") {
		t.Errorf("user content prefix not preserved: %q", s[:80])
	}
	if !strings.Contains(s, "REPOWISE:START") || !strings.Contains(s, "REPOWISE:END") {
		t.Error("markers should have been appended")
	}
}

func TestClaudeMd_Stdout(t *testing.T) {
	tmp, _, _ := repoFixture(t)
	if _, _, err := runRepowiseCmd(t, nil, "update", tmp); err != nil {
		t.Fatal(err)
	}
	// `update` auto-regenerates CLAUDE.md (matches the Python flow).
	// Delete it so we can assert --stdout doesn't re-create it.
	_ = os.Remove(filepath.Join(tmp, "CLAUDE.md"))

	stdout, _, err := runRepowiseCmd(t, nil, "claude-md", "--stdout", tmp)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(stdout, "REPOWISE:START") {
		t.Error("stdout output missing marker")
	}
	if _, err := os.Stat(filepath.Join(tmp, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Error("--stdout should not create a file")
	}
}

// TestUpdate_AutoRegeneratesClaudeMd documents the auto-regen
// contract: every `update` writes <repo>/CLAUDE.md.
func TestUpdate_AutoRegeneratesClaudeMd(t *testing.T) {
	tmp, _, _ := repoFixture(t)
	if _, _, err := runRepowiseCmd(t, nil, "update", tmp); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(filepath.Join(tmp, "CLAUDE.md"))
	if err != nil {
		t.Fatalf("update did not auto-write CLAUDE.md: %v", err)
	}
	if !strings.Contains(string(body), "REPOWISE:START") {
		t.Errorf("auto-regen output missing REPOWISE:START marker: %q", body)
	}
}

func TestClaudeMd_AcceptsLegacyAlias(t *testing.T) {
	tmp, _, _ := repoFixture(t)
	if _, _, err := runRepowiseCmd(t, nil, "update", tmp); err != nil {
		t.Fatal(err)
	}
	if _, _, err := runRepowiseCmd(t, nil, "generate-claude-md", tmp); err != nil {
		t.Fatalf("generate-claude-md alias: %v", err)
	}
	if _, err := os.Stat(filepath.Join(tmp, "CLAUDE.md")); err != nil {
		t.Errorf("alias should have written the file: %v", err)
	}
}

func TestClaudeMd_RoundTripDoesNotDuplicateMarkers(t *testing.T) {
	tmp, _, _ := repoFixture(t)
	if _, _, err := runRepowiseCmd(t, nil, "update", tmp); err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 3; i++ {
		if _, _, err := runRepowiseCmd(t, nil, "claude-md", tmp); err != nil {
			t.Fatalf("claude-md (run %d): %v", i, err)
		}
	}
	body, _ := os.ReadFile(filepath.Join(tmp, "CLAUDE.md"))
	s := string(body)
	if got := strings.Count(s, "REPOWISE:START"); got != 1 {
		t.Errorf("REPOWISE:START count = %d after 3 runs, want 1", got)
	}
	if got := strings.Count(s, "REPOWISE:END"); got != 1 {
		t.Errorf("REPOWISE:END count = %d after 3 runs, want 1", got)
	}
	if got := strings.Count(s, "Repowise MCP tools"); got != 1 {
		t.Errorf("'Repowise MCP tools' should appear exactly once, got %d", got)
	}
}
