// Package ui embeds the built dashboard SPA (Vite output under dist/) and
// serves it as an http.Handler. The vor daemon mounts Handler() as the
// catch-all route so a single binary serves both the REST API and the UI.
//
// dist/ is generated by `make ui` (cd ui && npm run build) and committed to
// the repo, so a plain `go build` (no Node toolchain) always embeds a real,
// self-consistent bundle. Regenerate and commit it whenever the UI changes.
package ui

import (
	"embed"
	"io/fs"
	"net/http"
	"path"
	"strings"
)

//go:embed all:dist
var distFS embed.FS

// Handler returns an http.Handler that serves the embedded SPA. Static asset
// requests are served directly; any other path falls back to index.html so
// client-side routing works on deep links / reloads.
func Handler() http.Handler {
	sub, err := fs.Sub(distFS, "dist")
	if err != nil {
		// Embed guarantees dist exists at compile time; this is unreachable.
		panic("ui: embedded dist/ missing: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(sub))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		reqPath := strings.TrimPrefix(path.Clean(r.URL.Path), "/")
		if reqPath == "" {
			reqPath = "index.html"
		}
		if _, err := fs.Stat(sub, reqPath); err != nil {
			// Unknown path → hand the SPA its entry point and let the
			// client router decide. 200, not 404: deep links are valid.
			r2 := r.Clone(r.Context())
			r2.URL.Path = "/"
			fileServer.ServeHTTP(w, r2)
			return
		}
		fileServer.ServeHTTP(w, r)
	})
}
