// Package wikitask registers wiki page generation as a post-pipeline task.
// It is a thin adapter: the actual generation lives in
// internal/generation/runner; this wires it into the task registry so it can
// be toggled per-repo from the dashboard and runs automatically after every
// index when an LLM provider is configured.
//
// Import for side effects to register the task:
//
//	import _ "github.com/HundredAcreStudio/vor/internal/generation/wikitask"
package wikitask

import (
	"context"
	"fmt"

	gmodels "github.com/HundredAcreStudio/vor/internal/generation/models"
	"github.com/HundredAcreStudio/vor/internal/generation/runner"
	"github.com/HundredAcreStudio/vor/internal/pipeline/tasks"
)

// TaskID is the stable identifier under which wiki generation is registered
// and toggled. Exported so callers (e.g. the generate CLI command) can refer
// to it without stringly-typing.
const TaskID = "wiki_generation"

// defaultKinds is the set of page kinds generated by the task. The
// architecture kind is defined in the models but not yet implemented, so it is
// intentionally excluded.
// defaultKinds: the architecture overview, per-directory module pages, and
// per-file pages. Symbol detail is intentionally NOT generated as standalone
// pages — each file's page already documents its key symbols, so symbols live
// inside the single file entry rather than fragmenting the wiki. (symbol_detail
// remains available on demand via `vor generate --kinds symbol_detail`.)
var defaultKinds = []gmodels.PageKind{
	gmodels.PageKindArchitecture,
	gmodels.PageKindDirectoryOverview,
	gmodels.PageKindFileOverview,
}

// Task generates per-file, per-directory, and per-symbol wiki pages.
type Task struct{}

func (Task) ID() string   { return TaskID }
func (Task) Name() string { return "Wiki Generation" }
func (Task) Description() string {
	return "Generate file, directory, and symbol overview pages with an LLM. Only changed units are regenerated on each run."
}

// DefaultEnabled is true: a repo with an LLM provider configured gets pages
// automatically. When no provider is set the task self-skips at Run time, so
// "default on" stays zero-config for repos without an LLM.
func (Task) DefaultEnabled() bool { return true }

// Order runs wiki generation before tasks that consume its pages (e.g.
// embedding generation), so on a single index pass pages exist to be embedded.
func (Task) Order() int { return 10 }

// Requires an LLM provider — the task self-skips without one.
func (Task) Requires() []string { return []string{tasks.RequiresProvider} }

// Run generates wiki pages for the repo. It skips (without error) when no LLM
// provider is configured. Generation is incremental — the runner skips pages
// whose source hash is unchanged — so running after every index is cheap.
func (Task) Run(ctx context.Context, tc tasks.Context) (tasks.Result, error) {
	if tc.Provider == nil {
		return tasks.Result{Skipped: true, Detail: "no LLM provider configured"}, nil
	}
	sum, err := runner.Run(ctx, runner.Options{
		RepoRoot:     tc.RepoRoot,
		RepositoryID: tc.RepositoryID,
		DB:           tc.DB,
		Provider:     tc.Provider,
		Model:        tc.Model,
		Kinds:        defaultKinds,
		Incremental:  tc.Incremental,
		Changed:      tc.Changed,
		Force:        tc.ForceWiki,
	})
	if err != nil {
		return tasks.Result{}, fmt.Errorf("wiki generation: %w", err)
	}
	detail := fmt.Sprintf("%d generated, %d skipped, %d pruned, %d errors (%d in / %d out tokens)",
		sum.GeneratedCount, sum.SkippedCount, sum.PrunedCount, sum.ErrorCount,
		sum.TotalInputTokens, sum.TotalOutputTokens)
	return tasks.Result{Detail: detail}, nil
}

func init() { tasks.Register(Task{}) }
